Repository MCLD/ocuda, pull requests merged in 2020-01, with the labels that each got.

#117 Adding EF Design and Tools to project
  src/Ops.Web/Ops.Web.csproj
Labels: bug

#119 Improve structured logging; page abstraction
  src/Ops.Controllers/Abstract/BaseController.cs
  src/Ops.Controllers/Areas/Admin/PagesController.cs
  src/Ops.Controllers/Areas/Admin/SocialCardsController.cs
  src/Ops.Controllers/Areas/ContentManagement/SectionController.cs
  src/Ops.Controllers/Areas/CoverIssue/ManagementController.cs
  src/Ops.Controllers/Areas/CoverIssue/ReportingController.cs
  src/Ops.Controllers/Areas/SiteManagement/FeatureController.cs
  src/Ops.Controllers/Areas/SiteManagement/LocationsController.cs
  src/Ops.Controllers/Areas/SiteManagement/RosterController.cs
  src/Ops.Controllers/Authorization/SectionManagerHandler.cs
  src/Ops.Controllers/ErrorController.cs
  src/Ops.Controllers/FilesController.cs
  src/Ops.Controllers/Filters/AuthenticationFilter.cs
  src/Ops.Controllers/Filters/RestoreModelStateAttribute.cs
  src/Ops.Controllers/HomeController.cs
  src/Ops.Controllers/UserContextProvider.cs
  src/Ops.Service/EmailService.cs
  src/Ops.Service/FeatureService.cs
  src/Ops.Service/FileService.cs
  src/Ops.Service/LdapService.cs
  src/Ops.Service/LocationService.cs
  src/Ops.Service/RosterService.cs
  src/Ops.Service/SiteSettingService.cs
  src/Ops.Web.WindowsAuth/Startup.cs
  src/Ops.Web/Ops.Web.csproj
  src/Ops.Web/Program.cs
  src/Ops.Web/Startup.cs
  src/Ops.Web/StartupHelper/DataContext.cs
  src/Promenade.Controllers/AboutController.cs
  src/Promenade.Controllers/Abstract/BaseController.cs
  src/Promenade.Controllers/Abstract/BasePageController.cs
  src/Promenade.Controllers/ErrorController.cs
  src/Promenade.Controllers/HomeController.cs
  src/Promenade.Controllers/LocationsController.cs
  src/Promenade.Controllers/NewsController.cs
  src/Promenade.Controllers/ServiceFacades/Controller.cs
  src/Promenade.Controllers/SubjectController.cs
  src/Promenade.Service/LanguageService.cs
  src/Promenade.Service/SiteSettingService.cs
  src/Promenade.Web/Program.cs
  src/Promenade.Web/Promenade.Web.csproj
  src/Promenade.Web/Startup.cs
  src/Promenade.Web/Views/Shared/PageNotFound.cshtml
  src/Promenade.Web/Web.cs
  src/Utility/Helpers/VersionHelper.cs
  src/Utility/Keys/Configuration.cs
  src/Utility/Logging/Configuration.cs
  src/Utility/Logging/Enrichment.cs
  src/Utility/Services/PathResolverService.cs
Labels: enhancement

#120 Fix Travis CI build
  .travis.yml
Labels: enhancement

#123 Fix and unify Docker build process
  docker-build.bash
Labels: enhancement

#126 Update docker-build.bash
  docker-build.bash
Labels: enhancement

#127 Minor fixes to Twitter social configuration
  src/Promenade.Controllers/TagHelpers/SocialCardTagHelper.cs
  src/Promenade.Models/Defaults/SiteSetting.cs
  src/Promenade.Models/Keys/SiteSetting.cs
  src/Promenade.Service/SocialCardService.cs
Labels: bug, enhancement

#128 Add Area Index Pages
  src/Ops.Controllers/AdminController.cs
  src/Ops.Controllers/Areas/Admin/PagesController.cs
  src/Ops.Controllers/Areas/Admin/SocialCardsController.cs
  src/Ops.Controllers/Areas/CoverIssue/ManagementController.cs
  src/Ops.Controllers/Areas/CoverIssue/ReportingController.cs
  src/Ops.Controllers/Areas/SiteManagement/CategoriesController.cs
  src/Ops.Controllers/Areas/SiteManagement/EmediaController.cs
  src/Ops.Controllers/Areas/SiteManagement/ExternalResourcesController.cs
  src/Ops.Controllers/Areas/SiteManagement/FeatureController.cs
  src/Ops.Controllers/Areas/SiteManagement/GroupsController.cs
  src/Ops.Controllers/Areas/SiteManagement/LocationsController.cs
  src/Ops.Controllers/Areas/SiteManagement/RosterController.cs
  src/Ops.Controllers/Areas/SiteManagement/SegmentsController.cs
  src/Ops.Controllers/Areas/SiteManagement/SiteSettingsController.cs
  src/Ops.Controllers/Areas/SiteManagement/UsersController.cs
  src/Ops.Controllers/ContentManagementController.cs
  src/Ops.Controllers/CoverIssueController.cs
  src/Ops.Controllers/SiteManagementController.cs
  src/Ops.Web/Views/Admin/Index.cshtml
  src/Ops.Web/Views/ContentManagement/Index.cshtml
  src/Ops.Web/Views/CoverIssue/Index.cshtml
  src/Ops.Web/Views/SiteManagement/Index.cshtml
Labels: enhancement

#125 Add management to location's structured data
  src/Ops.Controllers/Areas/SiteManagement/LocationsController.cs
  src/Ops.Service/LocationService.cs
  src/Ops.Web/Areas/SiteManagement/Views/Locations/LocationDetails.cshtml
  src/Ops.Web/Areas/SiteManagement/Views/Locations/_AddFeaturesPartial.cshtml
  src/Ops.Web/Areas/SiteManagement/Views/Locations/_AddGroupsPartial.cshtml
  src/Ops.Web/Areas/SiteManagement/Views/Locations/_EditGroupsPartial.cshtml
  src/Promenade.Controllers/LocationsController.cs
  src/Promenade.Controllers/ViewModels/Locations/LocationDetailViewModel.cs
  src/Promenade.Controllers/ViewModels/Locations/LocationViewModel.cs
  src/Promenade.Controllers/ViewModels/Locations/LocationsFeaturesViewModel.cs
  src/Promenade.Data/Promenade/LocationFeatureRepository.cs
  src/Promenade.Models/Entities/Feature.cs
  src/Promenade.Models/Entities/Location.cs
  src/Promenade.Models/Entities/LocationFeature.cs
  src/Promenade.Service/Interfaces/Repositories/ILocationFeatureRepository.cs
  src/Promenade.Service/LocationService.cs
  src/Promenade.Web/Styles/style.css
  src/Promenade.Web/Views/Locations/LocationDetails.cshtml
  src/Promenade.Web/Views/Locations/LocationFeatureDetails.cshtml
  src/Promenade.Web/Views/Locations/Locations.cshtml
  src/Promenade.Web/wwwroot/css/styles.min.css
  src/Utility/Logging/Enrichment.cs
Labels: bug, enhancement

#131 eMedia Improvements
  src/Ops.Data/PromenadeContext.cs
  src/Ops.Service/EmediaService.cs
  src/Ops.Web/Areas/SiteManagement/Views/Emedia/AddEmedia.cshtml
  src/Ops.Web/Areas/SiteManagement/Views/Emedia/EditEmedia.cshtml
  src/Ops.Web/Areas/SiteManagement/Views/Emedia/Index.cshtml
  src/Promenade.Controllers/EmediaController.cs
  src/Promenade.Data/Promenade/CategoryTextRepository.cs
  src/Promenade.Data/Promenade/EmediaCategoryRepository.cs
  src/Promenade.Data/Promenade/EmediaRepository.cs
  src/Promenade.Data/Promenade/EmediaTextRepository.cs
  src/Promenade.Data/PromenadeContext.cs
  src/Promenade.Models/Entities/Category.cs
  src/Promenade.Models/Entities/CategoryText.cs
  src/Promenade.Models/Entities/Emedia.cs
  src/Promenade.Models/Entities/EmediaText.cs
  src/Promenade.Service/EmediaService.cs
  src/Promenade.Service/Interfaces/Repositories/ICategoryTextRepository.cs
  src/Promenade.Service/Interfaces/Repositories/IEmediaCategoryRepository.cs
  src/Promenade.Service/Interfaces/Repositories/IEmediaRepository.cs
  src/Promenade.Service/Interfaces/Repositories/IEmediaTextRepository.cs
  src/Promenade.Web/Promenade.Web.csproj
  src/Promenade.Web/Startup.cs
  src/Promenade.Web/Views/Emedia/Index.cshtml
Labels: enhancement

#132 Improve location pages and styling
  src/Promenade.Controllers/ViewModels/Locations/LocationsFeaturesViewModel.cs
  src/Promenade.Web/Styles/style.css
  src/Promenade.Web/Views/Locations/LocationDetails.cshtml
  src/Promenade.Web/Views/Locations/Locations.cshtml
  src/Promenade.Web/wwwroot/css/styles.min.css
Labels: enhancement

#134 Fix warnings on site settings, improve locations
  src/Promenade.Service/SiteSettingService.cs
  src/Promenade.Web/Views/Locations/LocationDetails.cshtml
  src/Promenade.Web/Views/Locations/LocationFeatureDetails.cshtml
Labels: enhancement
