Repository MCLD/ocuda, pull requests merged in 2020-06, with the labels that each got.

#199 Add language display on admin contact scheduling
  src/Ops.Web/Areas/Contact/Views/Schedule/Index.cshtml
  src/Ops.Web/Ops.Web.csproj
  src/Promenade.Web/Promenade.Web.csproj
Labels: enhancement

#202 Fix carousel JavaScript IE11 compatibility
  src/Ops.Web/Ops.Web.csproj
  src/Promenade.Web/Promenade.Web.csproj
  src/Promenade.Web/Scripts/script.js
  src/Promenade.Web/wwwroot/js/scripts.min.js
Labels: bug

#206 Improve schedule request administration
  src/Ops.Controllers/Areas/Contact/ScheduleController.cs
  src/Ops.Controllers/ViewModels/Contact/ScheduleDetailViewModel.cs
  src/Ops.Data/Ops/EmailSetupTextRepository.cs
  src/Ops.Data/Ops/ScheduleLogRepository.cs
  src/Ops.Data/Promenade/ScheduleRequestRepository.cs
  src/Ops.Models/Entities/ScheduleLog.cs
  src/Ops.Service/Interfaces/Ops/Services/IScheduleRequestService.cs
  src/Ops.Service/Interfaces/Ops/Services/IScheduleService.cs
  src/Ops.Service/ScheduleNotificationService.cs
  src/Ops.Service/ScheduleRequestService.cs
  src/Ops.Service/ScheduleService.cs
  src/Ops.Service/UserService.cs
  src/Ops.Web/Areas/Contact/Views/Schedule/Details.cshtml
  src/Ops.Web/Areas/Contact/Views/Schedule/Index.cshtml
  src/Ops.Web/Ops.Web.csproj
  src/Promenade.Service/ScheduleService.cs
  src/Promenade.Web/Promenade.Web.csproj
Labels: bug, enhancement

#207 Fix date/time format provider for schedule emails
  src/Ops.Service/ScheduleNotificationService.cs
  src/Ops.Web/Ops.Web.csproj
  src/Promenade.Web/Promenade.Web.csproj
Labels: bug
