Repository MCLD/ocuda, pull requests merged in 2021-05, with the labels that each got.

#302 Fix job exception handling
  src/Ops.Controllers/Areas/ContentManagement/HomeController.cs
  src/Ops.DataProvider.SqlServer.Ops/Migrations/20210407030925_ops_v1.0.0.100.cs
  src/Ops.Service/Clients/ScreenlyClient.cs
  src/Ops.Service/DigitalDisplaySyncService.cs
  src/Ops.Service/ScheduleNotificationService.cs
  src/Ops.Web/JobScheduling/JobScopedProcessingService.cs
  src/Ops.Web/Ops.Web.csproj
  src/Promenade.Web/Promenade.Web.csproj
Labels: bug

#303 Remove concurrent job execution
  src/Ops.Web/JobScheduling/JobScopedProcessingService.cs
  src/Ops.Web/Ops.Web.csproj
  src/Promenade.Web/Promenade.Web.csproj
Labels: bug

#304 Improve digital display logging/status reporting
  src/Ops.Service/Clients/ScreenlyClient.cs
  src/Ops.Service/DigitalDisplaySyncService.cs
  src/Ops.Web/Ops.Web.csproj
  src/Promenade.Web/Promenade.Web.csproj
Labels: enhancement

#305 Fix logic error and logging for digital displays
  src/Ops.Service/Clients/ScreenlyClient.cs
  src/Ops.Web/Ops.Web.csproj
  src/Promenade.Web/Promenade.Web.csproj
Labels: bug

#309 Fix slide uploader indesign compatibility
  src/SlideUploader/Program.cs
  src/SlideUploader/Upload.cs
Labels: bug

#310 Update packages
  src/Ops.Data/Ops.Data.csproj
  src/Ops.DataProvider.SqlServer.Ops/Ops.DataProvider.SqlServer.Ops.csproj
  src/Ops.DataProvider.SqlServer.Promenade/Ops.DataProvider.SqlServer.Promenade.csproj
  src/Ops.Service/Ops.Service.csproj
  src/Ops.Web/Ops.Web.csproj
  src/Promenade.Data/Promenade.Data.csproj
  src/Promenade.DataProvider.SqlServer.Promenade/Promenade.DataProvider.SqlServer.Promenade.csproj
  src/Promenade.Web/Promenade.Web.csproj
  src/SlideUploader/SlideUploader.csproj
  src/Utility/Utility.csproj
  test/Ops/Ops.Data.Test/Ops.Data.Test.csproj
Labels: dependencies, developer

#311 Improve location editing
  src/Ops.Controllers/Areas/SiteManagement/LocationsController.cs
  src/Ops.Controllers/Areas/SiteManagement/SegmentsController.cs
  src/Ops.Controllers/Areas/SiteManagement/SocialCardsController.cs
  src/Ops.Controllers/Areas/SiteManagement/ViewModels/Location/LocationViewModel.cs
  src/Ops.Controllers/Areas/SiteManagement/ViewModels/Segment/DetailViewModel.cs
  src/Ops.Controllers/Areas/SiteManagement/ViewModels/SocialCards/DetailViewModel.cs
  src/Ops.Data/Promenade/SegmentRepository.cs
  src/Ops.Service/Interfaces/Ops/Services/ILocationService.cs
  src/Ops.Service/Interfaces/Promenade/Repositories/ISegmentRepository.cs
  src/Ops.Service/Interfaces/Promenade/Services/ISegmentService.cs
  src/Ops.Service/LocationService.cs
  src/Ops.Service/SegmentService.cs
  src/Ops.Web/Areas/SiteManagement/Views/Locations/Hours.cshtml
  src/Ops.Web/Areas/SiteManagement/Views/Locations/LocationDetails.cshtml
  src/Ops.Web/Areas/SiteManagement/Views/Locations/StructuredData.cshtml
  src/Ops.Web/Areas/SiteManagement/Views/Locations/_LocationPartial.cshtml
  src/Ops.Web/Areas/SiteManagement/Views/Segments/Detail.cshtml
  src/Ops.Web/Areas/SiteManagement/Views/SocialCards/Detail.cshtml
  src/Ops.Web/Ops.Web.csproj
  src/Promenade.Models/Entities/Location.cs
  src/Promenade.Web/Promenade.Web.csproj
  test/Ops/Ops.Data.Test/Ops.Data.Test.csproj
  test/i18n/i18n.Test/i18n.Test.csproj
Labels: enhancement
