Repository MCLD/ocuda, pull requests merged in 2021-02, with the labels that each got.

#284 Revert Docker sdk image
  Dockerfile_ops
  Dockerfile_promenade
Labels: developer

#285 Add social card to eMedia page
  src/Ops.Controllers/Areas/SiteManagement/EmediaController.cs
  src/Ops.Web/Ops.Web.csproj
  src/Promenade.Controllers/EmediaController.cs
  src/Promenade.Controllers/ViewModels/Emedias/EmediaViewModel.cs
  src/Promenade.Models/Defaults/SiteSetting.cs
  src/Promenade.Models/Keys/SiteSetting.cs
  src/Promenade.Web/Promenade.Web.csproj
  src/Promenade.Web/Views/Emedia/Index.cshtml
  test/i18n/i18n.Test/i18n.Test.csproj
Labels: dependencies, enhancement

#286 Fix scheduling ignoring buffer time
  src/Ops.Web/Ops.Web.csproj
  src/Promenade.Controllers/HelpController.cs
  src/Promenade.Web/Promenade.Web.csproj
Labels: bug

#288 Update packages, version
  src/Ops.Data/Ops.Data.csproj
  src/Ops.DataProvider.SqlServer.Ops/Ops.DataProvider.SqlServer.Ops.csproj
  src/Ops.DataProvider.SqlServer.Promenade/Ops.DataProvider.SqlServer.Promenade.csproj
  src/Ops.Web/Ops.Web.csproj
  src/Promenade.Data/Promenade.Data.csproj
  src/Promenade.DataProvider.SqlServer.Promenade/Promenade.DataProvider.SqlServer.Promenade.csproj
  src/Promenade.Web/Promenade.Web.csproj
  src/Utility/Utility.csproj
  test/Ops/Ops.Data.Test/Ops.Data.Test.csproj
Labels: developer

#289 Change scheduling time selection to dropdown list
  src/Ops.Web/Ops.Web.csproj
  src/Promenade.Controllers/HelpController.cs
  src/Promenade.Controllers/ViewModels/Help/ScheduleTimesViewModel.cs
  src/Promenade.Controllers/ViewModels/Help/ScheduleViewModel.cs
  src/Promenade.Web/Promenade.Web.csproj
  src/Promenade.Web/Views/Help/Schedule.cshtml
  src/Promenade.Web/Views/Help/ScheduleTimes.cshtml
Labels: enhancement
