Repository MCLD/ocuda, pull requests merged in 2021-12, with the labels that each got.

#400 Update build script
  build.bash
  src/SlideUploader/SlideUploader.csproj
  src/Utility/Utility.csproj
Labels: enhancement, developer

#392 Add Google Analytics for podcast plays
  src/Ops.Web/Ops.Web.csproj
  src/Promenade.Web/Promenade.Web.csproj
  src/Promenade.Web/Views/Podcasts/Episode.cshtml
  src/Promenade.Web/Views/Podcasts/Podcast.cshtml
Labels: enhancement

#404 Upgrade packages; modify health check; guideline
  .editorconfig
  src/Ops.Data/Ops.Data.csproj
  src/Ops.DataProvider.SqlServer.Ops/Ops.DataProvider.SqlServer.Ops.csproj
  src/Ops.DataProvider.SqlServer.Promenade/Ops.DataProvider.SqlServer.Promenade.csproj
  src/Ops.Service/Ops.Service.csproj
  src/Ops.Web/Ops.Web.csproj
  src/Ops.Web/Startup.cs
  src/Promenade.Data/Promenade.Data.csproj
  src/Promenade.DataProvider.SqlServer.Promenade/Promenade.DataProvider.SqlServer.Promenade.csproj
  src/Promenade.Web/Promenade.Web.csproj
  src/Promenade.Web/Startup.cs
  src/Utility/Utility.csproj
  test/Ops/Ops.Data.Test/Ops.Data.Test.csproj
Labels: dependencies, developer
