Repository MCLD/ocuda, pull requests merged in 2021-07, with the labels that each got.

#330 Change slide upload permission requirements
  src/Ops.Controllers/Areas/ContentManagement/DigitalDisplaysController.cs
  src/Ops.Web/Ops.Web.csproj
  src/Promenade.Web/Promenade.Web.csproj
Labels: bug

#331 Fix location search form in Chrome
  src/Ops.Web/Ops.Web.csproj
  src/Promenade.Web/Promenade.Web.csproj
  src/Promenade.Web/Views/Locations/Locations.cshtml
Labels: bug

#178 Adding Promenade Accessibility
  src/Ops.Web/Ops.Web.csproj
  src/Promenade.Web/Promenade.Web.csproj
  src/Promenade.Web/Styles/style.css
  src/Promenade.Web/Views/Emedia/Index.cshtml
  src/Promenade.Web/Views/Locations/LocationDetails.cshtml
  src/Promenade.Web/Views/Shared/_Layout.cshtml
  src/Promenade.Web/wwwroot/css/styles.min.css
  src/Utility/TagHelpers/ModalTagHelper.cs
Labels: enhancement

#340 Fix nativigation aria-labels to be titles
  dev/accessibility.md
  src/Ops.Web/Ops.Web.csproj
  src/Promenade.Web/Promenade.Web.csproj
  src/Promenade.Web/Views/Shared/_Layout.cshtml
Labels: enhancement

#336 Update packages
  src/Ops.Data/Ops.Data.csproj
  src/Ops.DataProvider.SqlServer.Ops/Ops.DataProvider.SqlServer.Ops.csproj
  src/Ops.DataProvider.SqlServer.Promenade/Ops.DataProvider.SqlServer.Promenade.csproj
  src/Ops.Web/Ops.Web.csproj
  src/Promenade.Data/Promenade.Data.csproj
  src/Promenade.DataProvider.SqlServer.Promenade/Promenade.DataProvider.SqlServer.Promenade.csproj
  src/Promenade.Web/Promenade.Web.csproj
  src/SlideUploader/SlideUploader.csproj
  src/Utility/Utility.csproj
  test/Ops/Ops.Data.Test/Ops.Data.Test.csproj
Labels: dependencies

#343 Improve eMedia accessibility
  src/Ops.Web/Ops.Web.csproj
  src/Promenade.Web/Promenade.Web.csproj
  src/Promenade.Web/Properties/launchSettings.json
  src/Promenade.Web/Styles/style.css
  src/Promenade.Web/Views/Emedia/Index.cshtml
  src/Promenade.Web/Views/Locations/LocationDetails.cshtml
  src/Promenade.Web/wwwroot/css/styles.min.css
  src/Utility/TagHelpers/ModalTagHelper.cs
Labels: enhancement

#345 Change eMedia heading links back to link-colored
  src/Ops.Web/Ops.Web.csproj
  src/Promenade.Web/Promenade.Web.csproj
  src/Promenade.Web/Views/Emedia/Index.cshtml
Labels: enhancement

#348 Add pagination accessibility
  src/Ops.Controllers/Areas/SiteManagement/PagesController.cs
  src/Ops.Controllers/Areas/SiteManagement/ViewModels/Pages/IndexViewModel.cs
  src/Ops.Service/ImageFeatureService.cs
  src/Ops.Service/Interfaces/Promenade/Services/IPageService.cs
  src/Ops.Service/PageService.cs
  src/Ops.Web/Areas/SiteManagement/Views/Pages/Index.cshtml
  src/Ops.Web/Ops.Web.csproj
  src/Promenade.Models/Entities/PageHeader.cs
  src/Promenade.Web/Promenade.Web.csproj
  src/Promenade.Web/Views/Shared/_Layout.cshtml
  src/Utility/TagHelpers/PaginateTagHelper.cs
  test/i18n/i18n.Test/i18n.Test.csproj
Labels: bug, dependencies, enhancement

#351 Add handling of concurrency issue with displays
  src/Ops.Data/Ops/DigitalDisplayRepository.cs
  src/Ops.Web/Ops.Web.csproj
  src/Promenade.Web/Promenade.Web.csproj
Labels: bug
