Repository MCLD/ocuda, pull requests merged in 2021-06, with the labels that each got.

#312 Remove unused references
  src/Ops.Controllers/Ops.Controllers.csproj
  src/Ops.Data/Ops.Data.csproj
  src/Ops.Web/Ops.Web.csproj
  src/Promenade.Data/Promenade.Data.csproj
  src/Promenade.Web/Promenade.Web.csproj
  src/SlideUploader/SlideUploader.csproj
  test/Ops/Ops.Data.Test/Ops.Data.Test.csproj
Labels: dependencies, developer

#313 Remove attempt to cache null PageLayoutTexts
  src/Ops.Web/Ops.Web.csproj
  src/Promenade.Service/PageService.cs
  src/Promenade.Web/Promenade.Web.csproj
Labels: bug, developer

#314 Better geocoding error handling; remove logging
  src/Ops.Controllers/Areas/SiteManagement/LocationsController.cs
  src/Ops.Web/Ops.Web.csproj
  src/Promenade.Service/CarouselService.cs
  src/Promenade.Web/Promenade.Web.csproj
Labels: bug, enhancement

#315 Fix issues with location feature editing/deleting
  src/Ops.Controllers/Areas/SiteManagement/LocationsController.cs
  src/Ops.Web/Areas/SiteManagement/Views/Locations/LocationDetails.cshtml
  src/Ops.Web/Ops.Web.csproj
  src/Promenade.Web/Promenade.Web.csproj
Labels: bug

#317 Fix podcast episode viewing; other improvements
  src/Ops.Data/Ops.Data.csproj
  src/Ops.DataProvider.SqlServer.Ops/Ops.DataProvider.SqlServer.Ops.csproj
  src/Ops.DataProvider.SqlServer.Promenade/Ops.DataProvider.SqlServer.Promenade.csproj
  src/Ops.Web/Areas/SiteManagement/Views/Locations/LocationDetails.cshtml
  src/Ops.Web/Ops.Web.csproj
  src/Promenade.Controllers/PodcastsController.cs
  src/Promenade.Data/Promenade.Data.csproj
  src/Promenade.Data/Promenade/PodcastItemRepository.cs
  src/Promenade.Data/Promenade/UrlRedirectRepository.cs
  src/Promenade.DataProvider.SqlServer.Promenade/Promenade.DataProvider.SqlServer.Promenade.csproj
  src/Promenade.Service/Interfaces/Repositories/IPodcastItemRepository.cs
  src/Promenade.Service/PodcastService.cs
  src/Promenade.Web/Promenade.Web.csproj
  src/Utility/Utility.csproj
  test/Ops/Ops.Data.Test/Ops.Data.Test.csproj
Labels: bug, dependencies

#318 Refactor Google API for proper HttpClient use
  src/Ops.Controllers/Areas/SiteManagement/LocationsController.cs
  src/Ops.Models/Extensions/Serialize.cs
  src/Ops.Models/GeocodePlace.cs
  src/Ops.Models/GeocodePlaceDetails.cs
  src/Ops.Service/Interfaces/Ops/Services/ILocationService.cs
  src/Ops.Service/LocationService.cs
  src/Ops.Web/Areas/SiteManagement/Views/Locations/LocationDetails.cshtml
  src/Ops.Web/Ops.Web.csproj
  src/Ops.Web/Startup.cs
  src/Promenade.Controllers/LocationsController.cs
  src/Promenade.Controllers/ViewModels/Locations/LocationViewModel.cs
  src/Promenade.Models/GeocodeResult.cs
  src/Promenade.Service/LocationService.cs
  src/Promenade.Web/Promenade.Web.csproj
  src/Promenade.Web/Startup.cs
  src/Promenade.Web/Views/Locations/Locations.cshtml
  src/Utility/Abstract/IGoogleClient.cs
  src/Utility/Clients/GoogleClient.cs
  src/Utility/Keys/Configuration.cs
  src/Utility/Models/Google/AddressComponent.cs
  src/Utility/Models/Google/GeocodeResult.cs
  src/Utility/Models/Google/Geometry.cs
  src/Utility/Models/Google/GoogleMultiResponse.cs
  src/Utility/Models/Google/GoogleSingleResponse.cs
  src/Utility/Models/Google/Location.cs
  src/Utility/Models/Google/PlaceDetails.cs
  src/Utility/Models/Google/TextSearchResult.cs
  src/Utility/Models/LocationSummary.cs
Labels: developer, enhancement

#321 Update MailKit/MimeKit
  src/Ops.Service/Ops.Service.csproj
  src/Ops.Web/Ops.Web.csproj
  src/Promenade.Web/Promenade.Web.csproj
  src/Utility/Utility.csproj
Labels: dependencies

#322 Add Podcast Accessibility Improvements
  src/Ops.Web/Ops.Web.csproj
  src/Promenade.Web/Promenade.Web.csproj
  src/Promenade.Web/Styles/style.css
  src/Promenade.Web/Views/Podcasts/Episode.cshtml
  src/Promenade.Web/Views/Podcasts/Index.cshtml
  src/Promenade.Web/Views/Podcasts/Podcast.cshtml
Labels: enhancement

#327 Fix coloring of digital displays in list
  src/Ops.Controllers/Areas/ContentManagement/ViewModels/DigitalDisplays/DisplayListViewModel.cs
  src/Ops.Web/Ops.Web.csproj
  src/Promenade.Web/Promenade.Web.csproj
Labels: bug

#328 Fix URL encoding of lat/long parameters
  src/Ops.Web/Ops.Web.csproj
  src/Promenade.Web/Promenade.Web.csproj
  src/Utility/Clients/GoogleClient.cs
Labels: bug

#329 Update test package
  src/Ops.Web/Ops.Web.csproj
  src/Promenade.Web/Promenade.Web.csproj
  test/Ops/Ops.Data.Test/Ops.Data.Test.csproj
Labels: dependencies
