Repository MCLD/ocuda, pull requests merged in 2021-08, with the labels that each got.

#358 Promenade general accessibility fixes
  src/Ops.Web/Ops.Web.csproj
  src/Promenade.Web/Promenade.Web.csproj
  src/Promenade.Web/Views/Shared/LayoutPage.cshtml
  src/Promenade.Web/Views/Shared/_Layout.cshtml
Labels: enhancement

#360 Add section navigation to Ops
  src/Ops.Controllers/Areas/ContentManagement/SectionController.cs
  src/Ops.Controllers/Areas/ContentManagement/ViewModels/Section/SectionIndexViewModel.cs
  src/Ops.Controllers/Filters/UserFilter.cs
  src/Ops.Controllers/ItemKey.cs
  src/Ops.Data/Ops/SectionRepository.cs
  src/Ops.Service/Interfaces/Ops/Repositories/ISectionRepository.cs
  src/Ops.Service/SectionService.cs
  src/Ops.Web/Areas/ContentManagement/Views/Section/Index.cshtml
  src/Ops.Web/Ops.Web.csproj
  src/Ops.Web/Styles/ops.css
  src/Ops.Web/Views/Home/Index.cshtml
  src/Ops.Web/Views/Shared/_Layout.cshtml
  src/Ops.Web/wwwroot/css/main.min.css
  src/Promenade.Web/Promenade.Web.csproj
  src/Utility/Keys/Cache.cs
Labels: enhancement

#362 Add indicator for home section posts
  src/Ops.Web/Ops.Web.csproj
  src/Ops.Web/Views/Home/Index.cshtml
  src/Promenade.Web/Promenade.Web.csproj
Labels: enhancement

#364 Remove client caching from Ops file downloads
  src/Ops.Controllers/Areas/ContentManagement/SectionController.cs
  src/Ops.Controllers/HomeController.cs
  src/Ops.Web/Ops.Web.csproj
  src/Promenade.Web/Promenade.Web.csproj
Labels: bug, ops

#365 Update packages
  src/Ops.Data/Ops.Data.csproj
  src/Ops.DataProvider.SqlServer.Ops/Ops.DataProvider.SqlServer.Ops.csproj
  src/Ops.DataProvider.SqlServer.Promenade/Ops.DataProvider.SqlServer.Promenade.csproj
  src/Ops.Web/Ops.Web.csproj
  src/Ops.Web/wwwroot/css/main.min.css
  src/Ops.Web/wwwroot/js/main.min.js
  src/Promenade.Data/Promenade.Data.csproj
  src/Promenade.DataProvider.SqlServer.Promenade/Promenade.DataProvider.SqlServer.Promenade.csproj
  src/Promenade.Web/Promenade.Web.csproj
  src/Utility/Helpers/ModelStateHelper.cs
  src/Utility/Utility.csproj
  test/Ops/Ops.Data.Test/Ops.Data.Test.csproj
  test/i18n/i18n.Test/i18n.Test.csproj
Labels: dependencies

#366 Fix Ops download file caching
  src/Ops.Controllers/Areas/ContentManagement/SectionController.cs
  src/Ops.Controllers/HomeController.cs
  src/Ops.Web/Ops.Web.csproj
  src/Promenade.Web/Promenade.Web.csproj
Labels: bug

#367 Attempt workaround for caching bug
  src/Ops.Controllers/Areas/ContentManagement/SectionController.cs
  src/Ops.Controllers/HomeController.cs
  src/Ops.Web/Ops.Web.csproj
  src/Promenade.Web/Promenade.Web.csproj
Labels: bug

#368 Roll back to ResponseCache
  src/Ops.Controllers/Areas/ContentManagement/SectionController.cs
  src/Ops.Controllers/HomeController.cs
  src/Ops.Web/Ops.Web.csproj
  src/Promenade.Web/Promenade.Web.csproj
Labels: bug
