Repository MCLD/ocuda, pull requests merged in 2022-02, with the labels that each got.

#423 Hide empty product inventory display; update deps
  src/Ops.Data/Ops.Data.csproj
  src/Ops.DataProvider.SqlServer.Ops/Ops.DataProvider.SqlServer.Ops.csproj
  src/Ops.DataProvider.SqlServer.Promenade/Ops.DataProvider.SqlServer.Promenade.csproj
  src/Ops.Service/Ops.Service.csproj
  src/Ops.Web.WindowsAuth/Ops.Web.WindowsAuth.csproj
  src/Ops.Web/Ops.Web.csproj
  src/Promenade.Data/Promenade.Data.csproj
  src/Promenade.DataProvider.SqlServer.Promenade/Promenade.DataProvider.SqlServer.Promenade.csproj
  src/Promenade.Web/Promenade.Web.csproj
  src/Promenade.Web/Views/Status/Product.cshtml
  src/Utility/Utility.csproj
  test/Ops/Ops.Data.Test/Ops.Data.Test.csproj
  test/i18n/i18n.Test/i18n.Test.csproj
Labels: bug, dependencies

#424 Update ImageSharp package
  src/Ops.Controllers/Ops.Controllers.csproj
  src/Ops.Web/Ops.Web.csproj
  src/Promenade.Web/Promenade.Web.csproj
Labels: dependencies, developer

#429 Fix Intranet section case sensitivity
  src/Ops.Service/SectionService.cs
  src/Ops.Web/Ops.Web.csproj
  src/Promenade.Web/Promenade.Web.csproj
Labels: bug
