Repository MCLD/ocuda, pull requests merged in 2022-04, with the labels that each got.

#440 Fix broken links on historical incidents
  src/Ops.Data/Ops.Data.csproj
  src/Ops.DataProvider.SqlServer.Ops/Ops.DataProvider.SqlServer.Ops.csproj
  src/Ops.DataProvider.SqlServer.Promenade/Ops.DataProvider.SqlServer.Promenade.csproj
  src/Ops.Web/Areas/Incident/Views/Shared/_IncidentPartial.cshtml
  src/Ops.Web/Ops.Web.csproj
  src/Promenade.Data/Promenade.Data.csproj
  src/Promenade.DataProvider.SqlServer.Promenade/Promenade.DataProvider.SqlServer.Promenade.csproj
  src/Promenade.Web/Promenade.Web.csproj
  src/Utility/Utility.csproj
  test/Ops/Ops.Data.Test/Ops.Data.Test.csproj
Labels: bug

#443 Fix product permissions lookup
  src/Ops.Controllers/Areas/SiteManagement/ProductsController.cs
  src/Ops.Web/Ops.Web.csproj
  src/Promenade.Web/Promenade.Web.csproj
Labels: bug

#444 Fix roster, digital display access
  src/Ops.Controllers/Areas/ContentManagement/DigitalDisplaysController.cs
  src/Ops.Controllers/Areas/ContentManagement/HomeController.cs
  src/Ops.Controllers/Areas/ContentManagement/ViewModels/Home/IndexViewModel.cs
  src/Ops.Web/Areas/ContentManagement/Views/DigitalDisplays/Index.cshtml
  src/Ops.Web/Areas/ContentManagement/Views/Home/Index.cshtml
  src/Ops.Web/Ops.Web.csproj
  src/Ops.Web/Views/Shared/_Layout.cshtml
  src/Promenade.Web/Promenade.Web.csproj
Labels: bug, enhancement

#445 Fix roster permission bug
  src/Ops.Controllers/Areas/ContentManagement/RosterController.cs
  src/Ops.Web/Ops.Web.csproj
  src/Promenade.Web/Promenade.Web.csproj
Labels: bug

#446 Additional roster permission fix
  src/Ops.Controllers/Areas/ContentManagement/RosterController.cs
  src/Ops.Web/Areas/ContentManagement/Views/Home/Index.cshtml
  src/Ops.Web/Ops.Web.csproj
  src/Promenade.Web/Promenade.Web.csproj
Labels: bug

#450 Display reason for not disabling on roster import
  src/Ops.Controllers/Areas/ContentManagement/RosterController.cs
  src/Ops.Models/Entities/User.cs
  src/Ops.Service/RosterService.cs
  src/Ops.Web/Areas/ContentManagement/Views/Roster/Changes.cshtml
  src/Ops.Web/Ops.Web.csproj
  src/Promenade.Web/Promenade.Web.csproj
Labels: enhancement

#453 Fix product inventory upload reading empty lines
  src/Ops.Controllers/Areas/SiteManagement/ProductsController.cs
  src/Ops.Service/ProductService.cs
  src/Ops.Web/Ops.Web.csproj
  src/Promenade.Web/Promenade.Web.csproj
Labels: bug
